languageCode = "en-us"
title = "Kyusho Aarhus"

# Main menu
[menu]
[[menu.main]]
name = "Kontakt"
pageRef = "/kontakt"
weight = 50

[[menu.main]]
name = "Klubbens formål"
pageRef = "/klubbensformål"
weight = 40

[[menu.main]]
name = "Blog"
pageRef = "/blog"
weight = 30

[[menu.main]]
name = "Om Kyusho"
pageRef = "/om-kyusho"
weight = 20

[[menu.main]]
name = "ToDo"
pageRef = "todo"
weight = 60


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[taxonomies]
category = "categories"
tag = "tags"


[outputs]
home = ["HTML", "RSS", "JSON"]
