name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download latest release asset
        run: |
          latest_release=$(gh release list --limit 1 | awk '{print $1}')
          echo "Latest release: $latest_release"

      - name: Unzip release asset
        run: |
          mkdir -p public
          unzip hugo-site.zip -d public

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public

