name: Deploy Hugo site to GitHub Pages

env:
  DEFAULT_HUGO_ENV: blowfish

on:
  workflow_dispatch:
    inputs:
      hugo_environment:
        description: 'Hugo environment to use for build'
        required: false
        default: 'blowfish'
        type: choice
        options:
          - blowfish
          - _default

  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.8'
          extended: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build test site
        run: hugo --minify --destination build_test --environment test
        env:
          HUGO_ENV: ${{ github.event.inputs.hugo_environment || env.DEFAULT_HUGO_ENV }}

      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build_test

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

# Remove?
      - name: Build prod site
        run: hugo --minify --destination build_prod --environment production
        env:
          HUGO_ENV: ${{ github.event.inputs.hugo_environment || env.DEFAULT_HUGO_ENV }}

      - name: Zip files
        run: cd build_prod && zip -r ../hugo-site.zip .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: latest_${{ github.sha }}
          release_name: "Release latest_${{ github.sha }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hugo-site.zip
          asset_name: hugo-site.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}